"""Tabular MDP definitions + offline dataset generation.

Four small-but-non-trivial environments are provided: a GridWorld, a River
Crossing puzzle, a Chain MDP, and a Tiny Random MDP. Every one is *exact* —
the full model (P, R, mu, gamma) is known — which is precisely what lets
``solver.py`` compute ground-truth policy values to arbitrary precision.

The offline dataset, however, is generated by a *behaviour policy* and is the
only thing OPE estimators are allowed to see.
"""

from __future__ import annotations

import numpy as np

from ..core.types import MDPSpec, TransitionDataset
from .solver import policy_value


class TabularMDP:
    """A known tabular MDP with logging + exact-evaluation support."""

    def __init__(
        self,
        name: str,
        P: np.ndarray,  # (S, A, S)
        R: np.ndarray,  # (S, A)
        mu: np.ndarray,  # (S,)
        gamma: float,
        terminals: np.ndarray | None = None,
    ) -> None:
        self.name = name
        self.P = np.asarray(P, dtype=float)
        self.R = np.asarray(R, dtype=float)
        self.mu = np.asarray(mu, dtype=float)
        if abs(self.mu.sum() - 1.0) > 1e-6:
            self.mu = self.mu / self.mu.sum()
        self.gamma = float(gamma)
        self.n_states, self.n_actions, _ = self.P.shape
        self.spec = MDPSpec(name, self.n_states, self.n_actions, self.gamma)
        self.terminals = (
            np.zeros(self.n_states, dtype=bool)
            if terminals is None
            else np.asarray(terminals, dtype=bool)
        )
        # force no transition out of terminal states
        for s in np.where(self.terminals)[0]:
            self.P[s] = 0.0
            self.P[s, :, s] = 1.0
            self.R[s] = 0.0

    # ----- exact evaluation -----
    def exact_value(self, policy_matrix: np.ndarray) -> float:
        return policy_value(policy_matrix, self.P, self.R, self.mu, self.gamma)

    def optimal_value(self) -> float:
        from .solver import optimal_policy

        return self.exact_value(optimal_policy(self.P, self.R, self.gamma))

    # ----- sampling -----
    def step(self, s: int, a: int, rng: np.random.Generator) -> tuple[int, float, bool]:
        s_next = int(rng.choice(self.n_states, p=self.P[s, a]))
        return s_next, float(self.R[s, a]), bool(self.terminals[s_next])

    def generate_dataset(
        self,
        policy_matrix: np.ndarray,
        n_episodes: int,
        max_steps: int,
        rng: np.random.Generator,
    ) -> TransitionDataset:
        S, A, Rr = [], [], []
        Ns, D, Bp, Eid, Init = [], [], [], [], []
        for ep in range(n_episodes):
            s = int(rng.choice(self.n_states, p=self.mu))
            done = False
            for t in range(max_steps):
                a = int(rng.choice(self.n_actions, p=policy_matrix[s]))
                s_next, r, done = self.step(s, a, rng)
                S.append(s)
                A.append(a)
                Rr.append(r)
                Ns.append(s_next)
                D.append(done)
                Bp.append(float(policy_matrix[s, a]))
                Eid.append(ep)
                Init.append(t == 0)
                s = s_next
                if done:
                    break
        return TransitionDataset(
            states=np.asarray(S, dtype=np.int64),
            actions=np.asarray(A, dtype=np.int64),
            rewards=np.asarray(Rr, dtype=np.float32),
            next_states=np.asarray(Ns, dtype=np.int64),
            dones=np.asarray(D, dtype=bool),
            behavior_probs=np.asarray(Bp, dtype=np.float32),
            episode_ids=np.asarray(Eid, dtype=np.int64),
            is_initial=np.asarray(Init, dtype=bool),
            spec=self.spec,
        )


# --------------------------------------------------------------------------
# Environment factories
# --------------------------------------------------------------------------


def _softmax(x: np.ndarray, tau: float = 1.0) -> np.ndarray:
    z = x / tau
    z = z - z.max(axis=-1, keepdims=True)
    e = np.exp(z)
    return e / e.sum(axis=-1, keepdims=True)


def make_gridworld(size: int = 5, gamma: float = 0.95) -> TabularMDP:
    """Classic 4-connected grid. Goal at bottom-right (reward +1, terminal)."""
    S = size * size
    A = 4  # up, right, down, left
    P = np.zeros((S, A, S))
    R = np.zeros((S, A))
    goal = S - 1
    terminals = np.zeros(S, dtype=bool)
    terminals[goal] = True
    R[:, :] = -0.01  # small step cost

    def coord(i: int) -> tuple[int, int]:
        return divmod(i, size)

    def idx(r: int, c: int) -> int:
        return r * size + c

    for s in range(S):
        if s == goal:
            continue
        r, c = coord(s)
        moves = {
            0: (max(r - 1, 0), c),  # up
            1: (r, min(c + 1, size - 1)),  # right
            2: (min(r + 1, size - 1), c),  # down
            3: (r, max(c - 1, 0)),  # left
        }
        for a, (rr, cc) in moves.items():
            ns = idx(rr, cc)
            P[s, a, ns] = 1.0
            # reward is awarded on the step that *enters* the goal
            if ns == goal:
                R[s, a] = 1.0
    mu = np.zeros(S)
    mu[0] = 1.0
    return TabularMDP("GridWorld", P, R, mu, gamma, terminals)


def make_river_crossing(width: int = 5, gamma: float = 0.95) -> TabularMDP:
    """Grid with a river band; only the bridge cell is safe to cross."""
    size = width
    S = size * size
    A = 4
    P = np.zeros((S, A, S))
    R = np.zeros((S, A))
    goal = S - 1
    terminals = np.zeros(S, dtype=bool)
    terminals[goal] = True
    R[:, :] = -0.02

    def coord(i: int) -> tuple[int, int]:
        return divmod(i, size)

    def idx(r: int, c: int) -> int:
        return r * size + c

    # river occupies row (size // 2); only column 0 is a bridge (safe)
    river_row = size // 2
    bridge_col = 0

    def is_river(r: int, c: int) -> bool:
        return r == river_row and c != bridge_col

    for s in range(S):
        if s == goal:
            continue
        r, c = coord(s)
        moves = {
            0: (max(r - 1, 0), c),
            1: (r, min(c + 1, size - 1)),
            2: (min(r + 1, size - 1), c),
            3: (r, max(c - 1, 0)),
        }
        for a, (rr, cc) in moves.items():
            if is_river(rr, cc):
                # falling in the river sends you back to start (state 0)
                P[s, a, 0] = 1.0
                R[s, a] = -1.0
            else:
                ns = idx(rr, cc)
                P[s, a, ns] = 1.0
                # reward is awarded on the step that *enters* the goal
                if ns == goal:
                    R[s, a] = 1.0
    mu = np.zeros(S)
    mu[0] = 1.0
    return TabularMDP("RiverCrossing", P, R, mu, gamma, terminals)


def make_chain_mdp(n: int = 10, gamma: float = 0.95) -> TabularMDP:
    """Chain of n states; two actions (left/right). Reward at the right end."""
    S = n
    A = 2  # 0=move left, 1=move right
    P = np.zeros((S, A, S))
    R = np.zeros((S, A))
    terminals = np.zeros(S, dtype=bool)
    terminals[n - 1] = True
    R[:, :] = -0.05
    R[n - 1, :] = 1.0
    for s in range(S):
        # left action: stay or go left (mostly left)
        P[s, 0, max(s - 1, 0)] = 0.9
        P[s, 0, min(s + 1, S - 1)] = 0.1
        # right action: mostly go right, but with some slip
        P[s, 1, min(s + 1, S - 1)] = 0.9
        P[s, 1, max(s - 1, 0)] = 0.1
    mu = np.zeros(S)
    mu[0] = 1.0
    return TabularMDP("ChainMDP", P, R, mu, gamma, terminals)


def make_tiny_random(n: int = 8, a: int = 2, gamma: float = 0.9, seed: int = 7) -> TabularMDP:
    """Small random MDP — a stress test for OPE variance/coverage."""
    rng = np.random.default_rng(seed)
    P = rng.dirichlet(np.ones(n), size=(n, a))
    R = rng.normal(0.0, 1.0, size=(n, a))
    mu = rng.dirichlet(np.ones(n))
    terminals = np.zeros(n, dtype=bool)
    terminals[n - 1] = True
    return TabularMDP("TinyRandom", P, R, mu, gamma, terminals)


def make_behaviour_policy(mdp: TabularMDP, tau: float = 0.6, seed: int = 0) -> np.ndarray:
    """A suboptimal-but-reasonable stochastic behaviour policy with full support.

    Full support (every action positive) is what keeps importance weights
    finite — essential for WIS to be well defined.
    """
    rng = np.random.default_rng(seed)
    rough = rng.normal(size=(mdp.n_states, mdp.n_actions))
    # bias towards the goal direction a little so it is not pure noise
    return _softmax(rough, tau=tau)


# convenience: a simple policy container used by the pipeline
class MatrixPolicy:
    """Wraps an (n_states, n_actions) matrix as a Policy."""

    def __init__(self, matrix: np.ndarray) -> None:
        self.matrix = np.asarray(matrix, dtype=float)
        self.n_states, self.n_actions = self.matrix.shape

    def probs(self, states: np.ndarray) -> np.ndarray:
        return self.matrix[np.asarray(states, dtype=np.int64)]

    def act(self, state: int, rng: np.random.Generator | None = None) -> int:
        rng = rng or np.random.default_rng()
        return int(rng.choice(self.n_actions, p=self.matrix[state]))

    def greedy(self) -> MatrixPolicy:
        pi = np.zeros_like(self.matrix)
        pi[np.arange(self.n_states), self.matrix.argmax(axis=1)] = 1.0
        return MatrixPolicy(pi)
